function cart(){
  const rows=cartRows();const subtotal=cartSubtotal();const shipping=rows.length?5:0;const total=subtotal+shipping;const saving=cartSaving();
  const groups={};rows.forEach(r=>{(groups[r.product.store]??=[]).push(r)});
  const productRow=({item,product:p})=>{const discount=p.old?Math.round((1-parsePrice(p.price)/parsePrice(p.old))*100):0;return `<div class="shopping-item"><div class="shopping-image"><img src="${absoluteProductImage(p.img)}" alt="${esc(p.name)}"></div><div class="shopping-info"><h3>${p.name}</h3><button class="shopping-store" data-action="open-store" data-store="${storesData.find(s=>s.name===p.store)?.id||''}">${p.store}</button><div class="shopping-price"><b>${displayPrice(p.price)}</b>${p.old?`<s>${displayPrice(p.old)}</s><em>خصم ${discount}%</em>`:''}</div><div class="shopping-delivery">${icon('circle-check',14)} متوفر وجاهز للشحن</div><div class="shopping-actions"><div class="quantity-control"><button data-action="cart-minus" data-id="${p.id}">−</button><span>${item.qty}</span><button data-action="cart-plus" data-id="${p.id}">+</button></div><div class="shopping-mini-actions"><button class="danger" data-action="cart-remove" data-id="${p.id}">${icon('trash-2',15)} حذف</button></div></div></div></div>`};
  return `<section class="screen">${simpleHead('حقيبة التسوق')}<div class="page-wrap"><div class="shopping-address"><div class="address-info"><span class="address-pin">${icon('map-pin',20)}</span><div><small>التوصيل إلى</small><strong>${state.activeAddress?`${esc(state.activeAddress.label)} - ${esc(state.activeAddress.area)}`:'اختر عنوان التوصيل'}</strong></div></div><button class="address-change" data-action="open-addresses">تغيير</button></div>
    ${rows.length?`${Object.entries(groups).map(([store,items])=>`<section class="cart-store-group"><div class="cart-store-head"><span>${icon('store',17)}</span><strong>${store}</strong><small>${items.length} منتج</small></div><div class="shopping-products">${items.map(productRow).join('')}</div><div class="cart-store-shipping">${icon('truck',16)} <span>يتم احتساب توصيل هذا المتجر حسب العنوان وشركة الشحن.</span></div></section>`).join('')}
      <div class="shopping-note"><button class="shopping-note-head" data-action="toggle-note"><span>إضافة ملاحظة للطلب</span><b>${icon(state.noteOpen?'chevron-up':'chevron-down',18)}</b></button>${state.noteOpen?`<div class="shopping-note-body"><textarea placeholder="اكتب ملاحظتك للبائع أو شركة التوصيل..."></textarea></div>`:''}</div>
      <div class="shopping-invoice"><h2>تفاصيل الفاتورة</h2><div class="invoice-line"><span>إجمالي المنتجات</span><b>${money(subtotal)}</b></div><div class="invoice-line"><span>رسوم التوصيل التقديرية</span><b>${money(shipping)}</b></div><div class="invoice-total"><span>المجموع الكلي</span><strong>${money(total)}</strong></div>${saving>0?`<div class="saving-message">${icon('circle-check',16)} أنت وفّرت ${money(saving)} في هذا الطلب</div>`:''}</div><div class="shopping-footer"><button class="shopping-checkout" data-nav="checkout">متابعة إلى الدفع <span>•</span> ${money(total)}</button></div>`:`<div class="empty-state rich-empty">${icon('shopping-bag',38)}<strong>حقيبة التسوق فارغة</strong><span>أضف منتجاتك المفضلة وارجع هنا لإتمام الطلب.</span><button class="red-action" data-nav="home">ابدأ التسوق</button></div>`}</div></section>${bottom('cart')}`
}
