import { Hono } from 'hono';
import { db } from '../db';
import { allowRoles,authRequired } from '../auth';
export const orderRoutes=new Hono();
orderRoutes.use('/orders/*',authRequired);

orderRoutes.post('/orders',async c=>{const a=c.get('auth') as {id:string};const b=await c.req.json();const client=await db.connect();try{await client.query('begin');const items=Array.isArray(b.items)?b.items:[];if(!items.length)throw new Error('Order requires items');const ids=items.map((x:any)=>x.variant_id);const variants=(await client.query(`select v.id,v.price_usd,v.stock,v.product_id,p.store_id from product_variants v join products p on p.id=v.product_id where v.id=any($1::uuid[])`,[ids])).rows;if(variants.length!==ids.length)throw new Error('Invalid variant');let total=0;const groups=new Map<string,any[]>();for(const item of items){const v=variants.find((x:any)=>x.id===item.variant_id);const q=Number(item.quantity);if(!Number.isInteger(q)||q<1||v.stock<q)throw new Error('Invalid quantity or stock');total+=Number(v.price_usd)*q;groups.set(v.store_id,[...(groups.get(v.store_id)||[]),{...item,v}]);}const order=(await client.query(`insert into orders(customer_id,address_id,status,payment_method,payment_status,currency_code,total) values($1,$2,'pending_admin_review',$3,'pending_review',$4,$5) returning *`,[a.id,b.address_id,b.payment_method,b.currency_code||'USD',total])).rows[0];for(const [storeId,g] of groups){const subtotal=g.reduce((s:number,x:any)=>s+Number(x.v.price_usd)*Number(x.quantity),0);const sub=(await client.query(`insert into suborders(order_id,store_id,status,subtotal,shipping_total,vendor_amount) values($1,$2,'pending_admin_review',$3,0,$3) returning *`,[order.id,storeId,subtotal])).rows[0];for(const x of g){await client.query(`insert into order_items(suborder_id,variant_id,quantity,unit_price,total) values($1,$2,$3,$4,$5)`,[sub.id,x.variant_id,x.quantity,x.v.price_usd,Number(x.v.price_usd)*Number(x.quantity)]);await client.query('update product_variants set stock=stock-$1 where id=$2',[x.quantity,x.variant_id]);}}await client.query('commit');return c.json({order},201)}catch(e:any){await client.query('rollback');return c.json({message:e.message||'Order failed'},400)}finally{client.release()}});

orderRoutes.post('/orders/:id/receipt',async c=>{const a=c.get('auth') as {id:string};const b=await c.req.json();const r=await db.query(`update orders set receipt_url=$1,payment_status='pending_review',updated_at=now() where id=$2 and customer_id=$3 and payment_method='transfer' returning id,payment_status,receipt_url`,[b.receipt_url,c.req.param('id'),a.id]);if(!r.rowCount)return c.json({message:'Order not found'},404);return c.json({order:r.rows[0]})});
orderRoutes.get('/orders',async c=>{const a=c.get('auth') as {id:string};return c.json({orders:(await db.query('select * from orders where customer_id=$1 order by created_at desc',[a.id])).rows})});

orderRoutes.use('/admin/orders/*',authRequired,allowRoles('admin'));
orderRoutes.post('/admin/orders/:id/approve',async c=>{const a=c.get('auth') as {id:string};const id=c.req.param('id');const client=await db.connect();try{await client.query('begin');const o=(await client.query('select * from orders where id=$1 for update',[id])).rows[0];if(!o)throw new Error('Order not found');if(o.payment_method==='transfer'&&!o.receipt_url)throw new Error('Receipt required');await client.query(`update orders set status='approved',payment_status='approved',approved_at=now(),approved_by=$2,updated_at=now() where id=$1`,[id,a.id]);const subs=(await client.query(`update suborders set status='accepted' where order_id=$1 and status='pending_admin_review' returning *`,[id])).rows;for(const s of subs){await client.query(`insert into vendor_payables(store_id,suborder_id,amount) values($1,$2,$3) on conflict(suborder_id) do nothing`,[s.store_id,s.id,s.vendor_amount]);await client.query(`insert into order_status_history(suborder_id,status,changed_by) values($1,'accepted',$2)`,[s.id,a.id]);}await client.query('commit');return c.json({approved:true,suborders:subs.length})}catch(e:any){await client.query('rollback');return c.json({message:e.message},400)}finally{client.release()}});

orderRoutes.get('/vendor/orders',authRequired,allowRoles('vendor','admin'),async c=>{const a=c.get('auth') as {id:string,role:string};const q=a.role==='admin'?`select so.* from suborders so where so.status<>'pending_admin_review' order by so.created_at desc`:`select so.* from suborders so join stores s on s.id=so.store_id where s.owner_id=$1 and so.status<>'pending_admin_review' order by so.created_at desc`;return c.json({orders:(await db.query(q,a.role==='admin'?[]:[a.id])).rows})});
orderRoutes.post('/vendor/orders/:id/status',authRequired,allowRoles('vendor','admin'),async c=>{const a=c.get('auth') as {id:string,role:string};const b=await c.req.json();const allowed=['accepted','processing','ready_for_delivery','with_courier','delivered'];if(!allowed.includes(b.status))return c.json({message:'Invalid status'},400);const own=a.role==='admin'?'':` and exists(select 1 from stores s where s.id=suborders.store_id and s.owner_id=$3)`;const args=a.role==='admin'?[b.status,c.req.param('id')]:[b.status,c.req.param('id'),a.id];const r=await db.query(`update suborders set status=$1 where id=$2 and status<>'pending_admin_review'${own} returning *`,args);if(!r.rowCount)return c.json({message:'Order not found'},404);await db.query('insert into order_status_history(suborder_id,status,changed_by) values($1,$2,$3)',[r.rows[0].id,b.status,a.id]);return c.json({order:r.rows[0]})});
