import { Hono } from 'hono';import { db } from '../db';import { authRequired,allowRoles } from '../auth';
export const promotionRoutes=new Hono();
promotionRoutes.use('/vendor/promotions/*',authRequired,allowRoles('vendor','admin'));
promotionRoutes.post('/vendor/promotions/discounts',async c=>{const a=c.get('auth') as any,b=await c.req.json();const own=await db.query('select p.id,p.store_id from products p join stores s on s.id=p.store_id where p.id=$1 and ($2=\'admin\' or s.owner_id=$3)',[b.product_id,a.role,a.id]);if(!own.rowCount)return c.json({message:'Product not found'},404);const r=await db.query(`insert into product_discounts(store_id,product_id,amount,enabled,starts_at,ends_at) values($1,$2,$3,true,$4,$5) returning *`,[own.rows[0].store_id,b.product_id,Number(b.amount),b.starts_at||null,b.ends_at||null]);return c.json({discount:r.rows[0]},201)});
promotionRoutes.post('/vendor/promotions/coupons',async c=>{const a=c.get('auth') as any,b=await c.req.json();const s=(await db.query('select * from stores where id=$1 and ($2=\'admin\' or owner_id=$3)',[b.store_id,a.role,a.id])).rows[0];if(!s)return c.json({message:'Store not found'},404);const r=await db.query(`insert into coupons(store_id,product_id,code,amount,status,starts_at,ends_at) values($1,$2,upper($3),$4,'pending_admin_review',$5,$6) returning *`,[s.id,b.product_id||null,b.code,Number(b.amount),b.starts_at||null,b.ends_at||null]);return c.json({coupon:r.rows[0]},201)});
promotionRoutes.delete('/vendor/promotions/coupons/:id',async c=>{const a=c.get('auth') as any;const r=await db.query(`delete from coupons where id=$1 and exists(select 1 from stores s where s.id=coupons.store_id and ($2='admin' or s.owner_id=$3)) returning id`,[c.req.param('id'),a.role,a.id]);return r.rowCount?c.json({deleted:true}):c.json({message:'Coupon not found'},404)});

promotionRoutes.use('/admin/promotions/*',authRequired,allowRoles('admin'));
promotionRoutes.get('/admin/promotions/coupons',async c=>c.json({coupons:(await db.query('select * from coupons order by created_at desc')).rows}));
promotionRoutes.post('/admin/promotions/coupons/:id/review',async c=>{const b=await c.req.json();if(!['approved','rejected'].includes(b.status))return c.json({message:'Invalid status'},400);const r=await db.query('update coupons set status=$1 where id=$2 returning *',[b.status,c.req.param('id')]);return r.rowCount?c.json({coupon:r.rows[0]}):c.json({message:'Coupon not found'},404)});

promotionRoutes.use('/returns/*',authRequired);
promotionRoutes.post('/returns',async c=>{const a=c.get('auth') as any,b=await c.req.json();const item=(await db.query(`select oi.*,p.returnable,o.customer_id,so.status from order_items oi join product_variants v on v.id=oi.variant_id join products p on p.id=v.product_id join suborders so on so.id=oi.suborder_id join orders o on o.id=so.order_id where oi.id=$1 and o.customer_id=$2`,[b.order_item_id,a.id])).rows[0];if(!item)return c.json({message:'Item not found'},404);if(item.status!=='delivered'||!item.returnable)return c.json({message:'Item is not returnable'},400);const q=Number(b.quantity);if(!Number.isInteger(q)||q<1||q>item.quantity)return c.json({message:'Invalid quantity'},400);const r=await db.query(`insert into return_requests(customer_id,order_item_id,quantity,reason) values($1,$2,$3,$4) returning *`,[a.id,b.order_item_id,q,b.reason]);return c.json({return:r.rows[0]},201)});
promotionRoutes.use('/admin/returns/*',authRequired,allowRoles('admin'));
promotionRoutes.get('/admin/returns',async c=>c.json({returns:(await db.query('select * from return_requests order by created_at desc')).rows}));
promotionRoutes.post('/admin/returns/:id/review',async c=>{const b=await c.req.json();if(!['approved','rejected'].includes(b.status))return c.json({message:'Invalid status'},400);const r=await db.query('update return_requests set status=$1,admin_note=$2,updated_at=now() where id=$3 returning *',[b.status,b.admin_note||null,c.req.param('id')]);return r.rowCount?c.json({return:r.rows[0]}):c.json({message:'Return not found'},404)});
