import { useEffect, useMemo, useState } from "react"
import type { RouteConfig } from "@mercurjs/dashboard-sdk"
import { Actions, Button, Card, Empty, Field, FormGrid, Message, Page, PageHeader, Status } from "../../spike-shared/ui"
import { Input } from "../../components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../components/ui/select"

declare const __BACKEND_URL__: string
export const config: RouteConfig = { label: "المنتجات", rank: 15 }

type Product = { id:string; title?:string; status?:string; thumbnail?:string; created_at?:string; seller?:{id?:string;name?:string;email?:string}; variants?:any[] }
const api=async(path:string,init?:RequestInit)=>{const response=await fetch(`${__BACKEND_URL__}${path}`,{credentials:"include",...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...(init?.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
const statusText=(value?:string)=>{const s=String(value||"").toLowerCase();if(["published","approved"].includes(s))return"منشور";if(["proposed","pending"].includes(s))return"بانتظار المراجعة";if(s==="rejected")return"مرفوض";if(s==="draft")return"مسودة";return value||"—"}
const statusTone=(value?:string):any=>{const s=String(value||"").toLowerCase();return ["published","approved"].includes(s)?"success":s==="rejected"?"danger":["proposed","pending"].includes(s)?"warning":"muted"}
function variantStock(variant:any):number|null{const direct=variant?.inventory_quantity??variant?.inventoryQuantity;if(typeof direct==="number"&&Number.isFinite(direct))return direct;const links=variant?.inventory_items||variant?.inventoryItems||[];let saw=false,total=0;for(const link of links){const inventory=link?.inventory||link?.inventory_item||link?.inventoryItem||link;const levels=inventory?.location_levels||inventory?.locationLevels||link?.location_levels||[];for(const level of levels){const available=level?.available_quantity??level?.availableQuantity;const stocked=level?.stocked_quantity??level?.stockedQuantity;const reserved=level?.reserved_quantity??level?.reservedQuantity??0;const value=available??(stocked!=null?Number(stocked)-Number(reserved||0):null);if(value!=null&&Number.isFinite(Number(value))){saw=true;total+=Number(value)}}}return saw?total:null}
function productStock(product:Product){const values=(product.variants||[]).map(variantStock).filter((value):value is number=>value!=null);return values.length?values.reduce((sum,value)=>sum+value,0):null}

export default function ProductsPage(){
 const[products,setProducts]=useState<Product[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState("")
 const load=async()=>{setLoading(true);try{const data=await api("/admin/spike/products");setProducts(data.products||[])}finally{setLoading(false)}}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 const visible=useMemo(()=>products.filter(product=>{const needle=query.trim().toLowerCase();const matches=!needle||String(product.title||"").toLowerCase().includes(needle)||String(product.seller?.name||product.seller?.email||"").toLowerCase().includes(needle)||(product.variants||[]).some(v=>String(v?.sku||"").toLowerCase().includes(needle));if(!matches)return false;if(filter==="all")return true;const status=String(product.status||"").toLowerCase();if(filter==="pending")return["pending","proposed"].includes(status);if(filter==="published")return["published","approved"].includes(status);return status===filter}),[products,query,filter])
 const act=async(id:string,action:"approve"|"reject")=>{try{let reason="";if(action==="reject")reason=prompt("سبب الرفض")||"تم رفض المنتج";setBusy(id);await api(`/admin/spike/products/${id}`,{method:"POST",body:JSON.stringify({action,reason})});setMessage(action==="approve"?"تمت الموافقة على المنتج ونشره.":"تم رفض المنتج.");await load()}catch(e:any){setMessage(e.message||"تعذر تنفيذ الإجراء")}finally{setBusy("")}}
 const pendingCount=products.filter(p=>["pending","proposed"].includes(String(p.status||"").toLowerCase())).length;const lowStockCount=products.filter(p=>{const stock=productStock(p);return stock!=null&&stock<=5}).length
 return <Page>
  <Card><PageHeader title="المنتجات" description="كل المنتجات المرفوعة من التجار مع الحالة والمخزون. إنشاء المنتجات متاح للتاجر فقط."/>{message&&<div className="mt-4"><Message>{message}</Message></div>}</Card>
  <div className="grid grid-cols-1 gap-3 md:grid-cols-3"><Card><span className="text-sm text-muted-foreground">إجمالي المنتجات</span><b className="mt-2 block text-2xl">{products.length}</b></Card><Card><span className="text-sm text-muted-foreground">بانتظار المراجعة</span><b className="mt-2 block text-2xl">{pendingCount}</b></Card><Card><span className="text-sm text-muted-foreground">مخزون منخفض ≤ 5</span><b className="mt-2 block text-2xl">{lowStockCount}</b></Card></div>
  <Card><FormGrid><Field label="بحث"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسم المنتج، التاجر أو SKU"/></Field><Field label="الحالة"><Select value={filter} onValueChange={v=>setFilter(v as string)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">الكل</SelectItem><SelectItem value="published">منشور</SelectItem><SelectItem value="pending">بانتظار المراجعة</SelectItem><SelectItem value="rejected">مرفوض</SelectItem><SelectItem value="draft">مسودة</SelectItem></SelectContent></Select></Field></FormGrid></Card>
  <Card>{loading?<Empty>جاري تحميل المنتجات...</Empty>:visible.length?<div className="overflow-x-auto"><Table className="min-w-[900px]"><TableHeader><TableRow><TableHead>المنتج</TableHead><TableHead>التاجر</TableHead><TableHead>الحالة</TableHead><TableHead>SKU</TableHead><TableHead>المخزون</TableHead><TableHead>تاريخ الإضافة</TableHead><TableHead>الإجراء</TableHead></TableRow></TableHeader><TableBody>{visible.map(product=>{const status=String(product.status||"").toLowerCase(),stock=productStock(product),sku=product.variants?.[0]?.sku||"—",canReview=["pending","proposed"].includes(status);return <TableRow key={product.id}><TableCell><div className="flex items-center gap-3">{product.thumbnail?<img src={product.thumbnail} alt="" className="size-12 rounded-xl object-cover"/>:<div className="grid size-12 place-items-center rounded-xl bg-muted font-bold">SP</div>}<b>{product.title||"بدون اسم"}</b></div></TableCell><TableCell>{product.seller?.name||product.seller?.email||"—"}</TableCell><TableCell><Status tone={statusTone(product.status)}>{statusText(product.status)}</Status></TableCell><TableCell><code>{sku}</code></TableCell><TableCell className={stock!=null&&stock<=5?"font-bold text-destructive":""}>{stock==null?"—":stock}{(product.variants?.length||0)>1&&<small className="ms-1 text-muted-foreground">{product.variants?.length} خيارات</small>}</TableCell><TableCell>{product.created_at?new Date(product.created_at).toLocaleDateString("ar-YE"):"—"}</TableCell><TableCell>{canReview?<Actions><Button disabled={busy===product.id} onClick={()=>act(product.id,"approve")}>موافقة</Button><Button tone="danger" disabled={busy===product.id} onClick={()=>act(product.id,"reject")}>رفض</Button></Actions>:<span className="text-muted-foreground">—</span>}</TableCell></TableRow>})}</TableBody></Table></div>:<Empty>لا توجد منتجات مطابقة.</Empty>}</Card>
 </Page>
}
